---
name: auto-context

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

env:
  CURL: 'curl -fsSL --netrc-optional'

jobs:
  update:
    runs-on: ubuntu-latest
    container: hansohn/terraform:latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CVE-2022-24765 fix
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Update context.tf
        id: update
        shell: bash
        run: |
            if [[ -f context.tf ]]; then
              ${{ env.CURL }} https://raw.githubusercontent.com/cloudposse/terraform-null-label/master/exports/context.tf -o context.tf
              if ! git diff --no-patch --exit-code context.tf; then
                echo "context.tf file has been updated. Rebuilding README.md"
                terraform-docs --output-mode inject --output-file README.md markdown .
              fi
            fi
            echo create_pull_request=true >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: cloudposse/actions/github/create-pull-request@0.31.0
        if: steps.update.outputs.create_pull_request == 'true'
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          committer: 'hansohnbot <82293428+hansohnbot@users.noreply.github.com>'
          author: 'hansohnbot <82293428+hansohnbot@users.noreply.github.com>'
          commit-message: updating context.tf from upstream origin
          title: update context.tf
          body: |-
            ## what
            This is an auto-generated PR that updates the `context.tf` file to the latest version from `cloudposse/terraform-null-label`

            ## why
            To support all the features of the `context` interface.
          branch: auto-update/context.tf
          base: main
          delete-branch: true
          labels: |
            auto-update
            context
